# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Unqualified
email: eero.helenius@kapsi.fi
description: > # this means to ignore newlines until "baseurl:"
  A litany of cogitations on code and other things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://eerohele.github.io" # the base hostname & protocol for your site
twitter_username: eerohelenius
github_username:  eerohele

# Build settings
markdown: kramdown
kramdown:
  input: GFM
